#!/usr/bin/ruby
# -*- encoding: utf-8 -*-
require File.join(File.dirname(__FILE__), '../lib/led_intermediator.rb')

class Main
  HELLO = 'ドーモ kasei_san です 撮影自由 アップロード自由'
  MESSAGES = %W[
    #{"安全ピンが好き 明日も働かない"}
    #{"お客が来るパンク デモ行進に近い 破壊的 スゴイ"}
    みなさんを守るオムラ社のマシンガン
    #{"カラテ十三段 殺人のライセンス 日本語を理解しない"}
    ビョウキ、トシヨリ、ヨロシサン
    おマミ
    そでん
    良く犬
    不如帰
    ちょっとやめないか
  ]

  def initialize
    @ctr = LedIntermediator.instance
    @ctr.set_finish_event(self)
    @cnt = 0
    init_str
  end

  def init_str
    @messages = MESSAGES.shuffle
  end

  def next_str
    str = if @cnt == 4
            @cnt = 0
            HELLO
          else
            if @messages == []
              init_str
            end
            @messages.shift
          end
    p "next_str(#{str})"
    @cnt += 1
    @ctr.set_str(str)
  end

  def finish
    p "next_str"
    next_str
  end
end

main = Main.new
main.next_str


sleep
